version: '3.9'

services:
  freegpt-webui:
    image: freegpt-webui
    container_name: freegpt-webui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
